
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows_94
 */
public class gui extends javax.swing.JFrame
{

	/**
	 * Creates new form gui
	 */
	public gui()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        inputPanel = new javax.swing.JPanel();
        inputBox = new javax.swing.JTextField();
        convertBtn = new javax.swing.JButton();
        infoLbl = new javax.swing.JLabel();
        outputPanel = new javax.swing.JPanel();
        yheLbl = new javax.swing.JLabel();
        bLbl = new javax.swing.JLabel();
        inLbl = new javax.swing.JLabel();
        outLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IP To Binary Converter");

        inputPanel.setBackground(new java.awt.Color(255, 255, 255));

        convertBtn.setText("Convert");
        convertBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                convertBtnActionPerformed(evt);
            }
        });

        infoLbl.setText("Please enter a 12 digit number or a number in the following format: XXX.XXX.XXX.XXX");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(inputBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(convertBtn))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(infoLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLbl)
                .addGap(10, 10, 10)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputPanel.setBackground(new java.awt.Color(255, 255, 255));

        yheLbl.setText("You have entered:");

        bLbl.setText("Binary:");

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(yheLbl)
                        .addGap(18, 18, 18)
                        .addComponent(inLbl))
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(bLbl)
                        .addGap(18, 18, 18)
                        .addComponent(outLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yheLbl)
                    .addComponent(inLbl))
                .addGap(18, 18, 18)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLbl)
                    .addComponent(outLbl))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_convertBtnActionPerformed
    {//GEN-HEADEREND:event_convertBtnActionPerformed
	String input = inputBox.getText(); //Get user input
	ArrayList<String> addr = new ArrayList(15); //ArrayList to store and organise user input
	
		if (input.length() > 15) //Input longer than 15 digit IPv4 address
		{
			System.out.println("Input too long to be IPv4 Address");
			System.exit(0);
		}
		else if (input.length() < 15) //Input shorter than IPv4 E.g. 192.168.1.1
		{
			filloutInput(input); //Modify input such as 192.168.25.3 into 192.168.025.003
//			System.out.println(addr);
		}
//		else
//			formatInput(input, addr); //Format input to include .'s
//		System.out.println(addr);	
    }//GEN-LAST:event_convertBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new gui().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bLbl;
    private javax.swing.JButton convertBtn;
    private javax.swing.JLabel inLbl;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JTextField inputBox;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel outLbl;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JLabel yheLbl;
    // End of variables declaration//GEN-END:variables

	private void formatInput(String input, ArrayList<String> addr) //Format input to include .'s
	{
		try
			{
				for (int i = 0; i < input.length(); i++)
				{
					if (i == 3 || i == 6 || i == 9) //Add .'s to create 000.000.000.000 format
					{
						addr.add(".");
					}
					String inpS = input.substring(i, i+1);
					addr.add(inpS);
				}
			} catch(NumberFormatException n){System.out.println("Non-numeric value was entered");}
	}

	private void filloutInput(String input) //Modify input such as 192.168.25.3 into 192.168.025.003
	{
		String filledInput = "";
		for (int i = 0; i < 16; i++)
		{
			if (i == 3 || i == 6 || i == 9)
			{
				filledInput += ".";
			}
			try
			{
				filledInput += input.substring(i, i+1);
			} catch(StringIndexOutOfBoundsException s){System.out.println("End of String Reached");}
			System.out.println(filledInput);
		}
		System.out.println(filledInput);
	}
}
